apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    git: https://github.com/dmc-tech/hello_arc.git
    path: charts/ingress-nginx
    ref: master
  values:
    controller:
      admissionWebhooks: 
        enabled: false
      replicaCount: 3
    defaultBackend:
      replicaCount: 3
