apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  releaseName: nginx-ingress
  chart:
    git: https://github.com/dmc-tech/hello_arc.git
    path: charts/nginx-ingress
    ref: master
  values:
    controller:
      replicaCount: 3
    defaultBackend:
      replicaCount: 3
