apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  releaseName: nginx-ingress
  chart:
    git: https://github.com/dmc-tech/hello_arc.git
    path: charts/nginx-ingress
    ref: master
  values:
    image:
      repository: https://kubernetes.github.io/ingress-nginx
      tag: "3.11.1"
    replicaCount: 3
